name: CI

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.100'

      - name: Build and test
        run: |
          dotnet build -c Release
          dotnet test -c Release --no-build --verbosity normal

      - name: Publish Console App
        if: success()
        run: |
          dotnet publish -c Release -r win10-x64 --self-contained Louis.Martin.FeatureMatching.Console/Louis.Martin.FeatureMatching.Console.csproj

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: published-app
          path: ./bin/Release/netcoreapp3.1/win10-x64/publish
